package com.captchatheai.backend.lobby;

public enum LobbyPhase {
	INTERMISSION,
	STARTING,
	INTRO,
	QUESTION_START,
	QUESTION,
	QUESTION_DISCONNECT,
	QUESTION_EMPTY,
	ANSWER_START,
	ANSWER,
	DISCUSS_START,
	DISCUSS,
	VOTING,
	VOTING_RESTART,
	REVEAL_START,
	REVEAL,
	REVEAL_TIE,
	REVEAL_END,
	AI_PLAYER_WON,
	AI_PLAYER_FAILED_TO_RESPOND,
	HUMAN_PLAYERS_WON,
	NOT_ENOUGH_PLAYERS;
	
}
