package com.captchatheai.backend.lobby;

public enum LobbyPhase {
	INTERMISSION,
	STARTING,
	INTRO,
	QUESTION_ANNOUNCEMENT,
	QUESTION,
	QUESTION_DISCONNECT,
	QUESTION_EMPTY,
	ANSWER_ANNOUNCEMENT,
	ANSWER,
	DISCUSS_ANNOUNCEMENT,
	DISCUSS,
	VOTING,
	VOTING_RESTART,
	REVEAL_ANNOUNCEMENT,
	REVEAL,
	REVEAL_TIE,
	ELIMINATION,
	AI_PLAYER_WON,
	AI_PLAYER_FAILED_TO_RESPOND,
	HUMAN_PLAYERS_WON,
	NOT_ENOUGH_PLAYERS;
	
}
